version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_IMAGE_TAG:-2017-latest}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - ../src/leaf/src/db/build/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ../src/leaf/src/db/build/configure-db.sh:/usr/local/bin/configure-db.sh:ro
      - ../src/leaf/src/db/build/setup.sql:/opt/mssql/setup.sql:ro

      - ../src/leaf/src/db/build/LeafDB.Schema.sql:/docker-entrypoint-initdb.d/00LeafDB.Schema.sql:ro
      - ../src/leaf/src/db/build/LeafDB.Init.sql:/docker-entrypoint-initdb.d/01LeafDB.Init.sql:ro
      # https://github.com/uwrit/leaf-scripts/blob/master/GEMs/LeafDB.GEMs.sql
      - ../src/leaf-scripts/GEMs/LeafDB.GEMs.sql:/docker-entrypoint-initdb.d/02LeafDB.GEMs.sql:ro

    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    networks:
      - internal

  clin-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: db-user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-clindb.sql:/docker-entrypoint-initdb.d/init-clindb.sql:ro
    networks:
      - internal

  coreapi:
    environment:
      LEAF_LOGOUT_URI: https://${LEAF_DOMAIN}/oauth2/sign_out
    image: ghcr.io/uwcirg/leaf-api:${LEAF_API_IMAGE_TAG:-latest}
    build:
      context: ../src/leaf/src/server
    labels:
      - traefik.enable=true
    networks:
      - ingress
      - internal

  node:
    image: ghcr.io/uwcirg/leaf-frontend:${LEAF_FRONTEND_IMAGE_TAG:-latest}
    environment:
      REACT_APP_MATOMO_SITE_ID: ${REACT_APP_MATOMO_SITE_ID}
    build:
      context: ../src/leaf/src/ui-client
    entrypoint:
      # override default NodeJS docker entrypoint script with our own
      - /opt/leaf/node-entrypoint-override.sh
      - /usr/local/bin/docker-entrypoint.sh
    volumes:
      - ./node-entrypoint-override.sh:/opt/leaf/node-entrypoint-override.sh:ro
    command:
      - npm
      - start
    labels:
      - traefik.enable=true
    networks:
      - ingress
