-- MariaDB initialization script; run on first start only
CREATE DATABASE IF NOT EXISTS alive;
GRANT SELECT, CREATE TEMPORARY TABLES ON alive.* TO `db-user`@`%`;

CREATE DATABASE IF NOT EXISTS hymtruth;
GRANT SELECT, CREATE TEMPORARY TABLES ON hymtruth.* TO `db-user`@`%`;

CREATE DATABASE IF NOT EXISTS mash;
GRANT SELECT, CREATE TEMPORARY TABLES ON mash.* TO `db-user`@`%`;

CREATE DATABASE IF NOT EXISTS mstudy;
GRANT SELECT, CREATE TEMPORARY TABLES ON mstudy.* TO `db-user`@`%`;

CREATE DATABASE IF NOT EXISTS radar;
GRANT SELECT, CREATE TEMPORARY TABLES ON radar.* TO `db-user`@`%`;
