version: "3"
services:
  gateway-mssql:
    extends:
      file: ../common-services.yaml
      service: mssql
    volumes:
      - leaf-gateway-mssql:/var/opt/mssql

  gateway-coreapi:
    extends:
      file: ../common-services.yaml
      service: coreapi
    volumes:
      - ../gateway/keys:/.keys:ro
      - ../gateway/appsettings.json:/app/API/appsettings.json:ro
    environment:
      LEAF_JWT_KEY_PW: ${GATEWAY_JWT_KEY_PW}
      LEAF_APP_DB: Server=gateway-mssql,1433;Database=LeafDB;uid=sa;Password=${MSSQL_SA_PASSWORD}
      LEAF_CLIN_DB: Server=clin-db,3306;Database=gateway;uid=db-user;Password=${MYSQL_PASSWORD}
    labels:
      - traefik.http.routers.gateway-coreapi-${COMPOSE_PROJECT_NAME}.rule=Host(`${LEAF_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.gateway-coreapi-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.gateway-coreapi-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.gateway-coreapi-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

  node:
    extends:
      file: ../common-services.yaml
      service: node
    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway-node-${COMPOSE_PROJECT_NAME}.rule=Host(`${LEAF_DOMAIN}`)
      - traefik.http.routers.gateway-node-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.gateway-node-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.gateway-node-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

  clin-db:
    extends:
      file: ../common-services.yaml
      service: clin-db

volumes:
  leaf-gateway-mssql:
  mysql-data:

networks:
  # internal network for backing services
  internal:
  # ingress network
  ingress:
    external: true
    name: external_web
