services:
  auth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    # oauth2-proxy does not EXPOSE (advertise) the ports it listens on in its docker image
    expose:
      - 4180
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      # OAUTH2_PROXY_CLIENT_ID: leaf_prod_oauth2_proxy
      OAUTH2_PROXY_CLIENT_ID: 'urn:leaf:iss:dev.leaf.tld'

      OAUTH2_PROXY_REVERSE_PROXY: "true"
      # needed to set X-Auth-Request-Email
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"

      # when authenticated, return a static 202 response
      # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#forwardauth-with-static-upstreams-configuration
      OAUTH2_PROXY_UPSTREAMS: static://202

      # general cookie settings
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_EXPIRE: 30m
      OAUTH2_PROXY_COOKIE_REFRESH: 1m
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      # TODO test how leaf handles usernames that are not email addresses
      # base session cookie on Keycloak username (email not always set in Keycloak)
      OAUTH2_PROXY_USER_ID_CLAIM: preferred_username

      # OIDC integration settings
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_SCOPE: openid profile email
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.cirg.washington.edu/realms/hivsuccess-upload

      # security settings
      OAUTH2_PROXY_COOKIE_DOMAINS: .${LEAF_DOMAIN}
      OAUTH2_PROXY_WHITELIST_DOMAINS: .${LEAF_DOMAIN}
    # TODO fixup relative path
    env_file:
      - ../radar/auth-proxy.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth-proxy-${COMPOSE_PROJECT_NAME}.rule=PathPrefix(`/oauth2`) && (Host(`auth-proxy.${LEAF_DOMAIN}`) || (Host(`leaf-auth.radar.${LEAF_DOMAIN}`)))
      - traefik.http.routers.auth-proxy-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.auth-proxy-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.auth-proxy-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

      # https://oauth2-proxy.github.io/oauth2-proxy/configuration/integration/#forwardauth-with-static-upstreams-configuration
      - traefik.http.middlewares.oidc-auth-${COMPOSE_PROJECT_NAME}.forwardAuth.address=http://auth-proxy-${COMPOSE_PROJECT_NAME}:4180/
      - traefik.http.middlewares.oidc-auth-${COMPOSE_PROJECT_NAME}.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.oidc-auth-${COMPOSE_PROJECT_NAME}.forwardAuth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Authorization

      # TODO dynamically look up from OIDC tokens
      # add Leaf group to all users via header
      #- traefik.http.middlewares.leaf-groups-${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.gws-groups=uw_leaf_users
      #- traefik.http.middlewares.leaf-groups-${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.gws-groups=uw_leaf_identified
      - traefik.http.middlewares.leaf-groups-${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.gws-groups=uw_leaf_admins

    networks:
      ingress:
        aliases:
          - auth-proxy-${COMPOSE_PROJECT_NAME}
      internal:

  node:
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && !PathPrefix(`/api`)
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:
  radar-coreapi:
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && PathPrefix(`/api`) && !Path(`/api/user`)
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

      # https://leafdocs.rit.uw.edu/installation/installation_steps/9_saml2/#route-protection-setup
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && Path(`/api/user`)
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:

  whoami:
    image: containous/whoami:v1.5.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.rule=Host(`whoami.radar.${LEAF_DOMAIN}`)
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:
