services:
  node:
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && !PathPrefix(`/api`)
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-frontend-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:
  radar-coreapi:
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && PathPrefix(`/api`) && !Path(`/api/user`)
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-unauth-api-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

      # https://leafdocs.rit.uw.edu/installation/installation_steps/9_saml2/#route-protection-setup
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.rule=Host(`leaf-auth.radar.${LEAF_DOMAIN}`) && Path(`/api/user`)
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-api-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:

  whoami:
    image: containous/whoami:v1.5.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.rule=Host(`whoami.radar.${LEAF_DOMAIN}`)
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.middlewares=oidc-auth-${COMPOSE_PROJECT_NAME},leaf-groups-${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.leaf-auth-whoami-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      ingress:
      internal:
